### ISSUE TITLE
sky_engine/blob/master/sky/packages/sky/README.md

### ISSUE THREAD

**Issue by gmesch** [domokit/sky_engine#1003]
I tried to follow https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/README.md

Here is where it failed on both osx and linux:

Linux:

$ sudo apt-get install android-tools-adb

$ ./packages/sky/sky_tool start --checked && adb logcat -s sky chromium

ERROR: "/usr/bin/adb" is too old. Need 1.0.32 or later.

OSX:

$ pub update

Downloading material_design_icons 0.0.2...

Timed out after 30.0s while downloading https://pub.dartlang.org/packages/material_design_icons/versions/0.0.2.tar.gz.

This is likely a transient error. Please try again later.

(but it persists for over two hours now)

**Comment by abarth** [comment]
I just pushed a new version of material_design_icons that is half the size of the old one.  Hopefully that will fix the timeout issue you're seeing.

**Comment by abarth** [comment]
I'd also be interested to know which version of `pub` you're using.  Newer versions should have a longer timeout.

Also, what version of Linux are you using?  We need to investigate which versions of Linux have newer versions of `adb` in their package managers.

**Comment by gmesch** [comment]
I was using the non- --devel version of pub. Running brew install dart
--devel fixed the problem.

The adb problem on my linux workstation I fixed by installing android sdk
manually and adjusting path. It's still odd that the default version of the
managed package is so old, though.

Thanks a lot!

**Comment by abarth** [comment]
I've updated the instructions to recommend `--devel` and to suggest installing the Android SDK manually.

Thanks!
