### ISSUE TITLE
Missing bindings for drawVertices in Skia-bindings

### ISSUE THREAD

**Issue by vlidholt** [domokit/sky_engine#1020]
Code for testing bindings to drawVertices (pushed to branch in my Github repo)
https://github.com/vlidholt/sky_engine/tree/drawVertices

Specific file:
https://github.com/vlidholt/sky_engine/blob/drawVertices/sky/packages/sky/example/game/test_spritemesh.dart

Vik

**Comment by abarth** [comment]
You landed this, right?
