### ISSUE TITLE
Considering a different way to retrieve parentData

### ISSUE THREAD

**Issue by sethladd** [domokit/sky_engine#1033]
Right now, in RenderObject, we see this line:

```
dynamic parentData; // TODO(ianh): change the type of this back to ParentData once the analyzer is cleverer
```

and uses like this:

```
// inside some parent
assert(child.parentData is SpecificThing);
SpecificThing localParentData = child.parentData;
localParentData.callMethodOnlyOnSpecificThing(); // no warning
```

My understanding is that a parent is able to set a specific type of parentData on a child, and the parent should expect to get that parentData back from the child. The parent wants to treat the returned parentData as a specific type.

One idea is to invert who is responsible for returning the parentData. What if we asked the parent for that?

```
// inside some parent
this.parentDataFrom(child).callMethodOnlyOnSpecificThing(); // no warning!
```

Note: RenderObject's parentData might still be dynamic. However, for each subclass of RenderObject, there is a method that returns a specific type of parentData. Something like:

```
class SpecificParent extends RenderObject {
  SpecificParentData parentDataFrom(child) => child.parentData;
}

class OtherSpecificParent extends RenderObject {
  OtherSpecificParentData parentDataFrom(child) => child.parentData;
}
```

Of course, RenderObject would have an abstract method called parentDataFrom() that returns dynamic. The contract would be that subclasses would implement that method and use a more specific return type. That's OK by Dart!

**Comment by sethladd** [comment]
cc @Hixie

**Comment by Hixie** [comment]
The problem is now we're replacing every call to child.parentData with a call to a method that then calls child.parentData. Also, it's a lot uglier.

IMHO a better solution is to have the analyzer figure out (either through brute force or by an annotation) that once you asserted the type of a child's parent data, that child's parent data will have that type for the rest of the method body (unless you call a codepath that somehow changes it). Right now the analyzer already does this for local variables (which are of course a much simpler problem, since code outside the current block can't change the type of a local variable).

**Comment by sethladd** [comment]
Code like `SpecificThing localParentData = child.parentData;` can act like an assert... in checked mode, that will fail until parentData is a SpecificThing.

What do you think about:

```
// inside some parent
// assert(child.parentData is SpecificThing); <== no need for this, if you have the second line
SpecificThing localParentData = child.parentData;
localParentData.callMethodOnlyOnSpecificThing(); // no warning
```

**Comment by Hixie** [comment]
The assert looks like an assert. Having a local variable like that is asking for someone to come through and "clean up" the code later.

**Comment by sethladd** [comment]
> The assert looks like an assert.

True, but it only does one thing.

This (`SpecificThing localParentData = child.parentData;`) does two things in Dart:

* in checked mode, insert a dynamic type assertion, effectively duplicating the assert.
* gives you better code completion and eliminates incorrect warnings.

So, in Dart, you could consider checked mode and type annotations a much better "assert", if you're just trying to say "this thing is a type Foo".

**Comment by sethladd** [comment]
So, tldr:

* remember that Dart's checked mode dynamically inserts type assertions
* if you want great warnings and code completion, use a type annotation with a local variable when "casting"
* the analyzer won't use an assert on a getter as a way to disable warnings after the assert

Go from:

```
assert(child.parentData is SpecificThing);
SpecificThing localParentData = child.parentData; // two asserts for the same thing in checked mode
```

To just:

```
SpecificThing localParentData = child.parentData; // type assertion in checked mode
```

That all said, going to close because no sense keeping this open. Clean issue trackers FTW!
