### ISSUE TITLE
sky_tool returns an exit code of 0 for some failures

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_engine#1052]
When I run `sky_tool start` for a sky app w/o a device of any kind connected, I see:

```
error: device not found
WARNING: No running simulators found
```

which is right, but the script exits with an exit code of `0`. It would be great to return a non-zero result; I use this code in atom to know when a run succeeded or not.

**Comment by devoncarew** [comment]
@iansf

**Comment by iansf** [comment]
https://github.com/domokit/sky_engine/pull/1054 should fix this

**Comment by devoncarew** [comment]
Great, thanks!
