### ISSUE TITLE
sky_tool emits a warning even on a successful run

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_engine#1053]
When I run sky_tool with a android device connected I see a warning even on a successful run. The app successfully launches on the device but sky_tool warns that it couldn't find a simulator to run on.

```
6532 KB/s (7551356 bytes in 1.128s)
	pkg: /data/local/tmp/SkyShell.apk
Success
5 KB/s (40 bytes in 0.007s)
WARNING: No running simulators found
```

If we have a successful launch on one device we probably shouldn't complain about a missing simulator...

@iansf

**Comment by iansf** [comment]
I'm assuming this isn't blocking you -- let me know if that's not the case.  Otherwise, I'll just fix this as part of the translation to dart.

**Comment by devoncarew** [comment]
Thanks - it's not critical in the short term. Happy to wait on this for the translation to dart :)
