### ISSUE TITLE
When exporting libs from src/ , consider using relative URIs

### ISSUE THREAD

**Issue by sethladd** [domokit/sky_engine#1057]
Was poking around, and came across https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/widgets.dart

with lots of exports like:

```
export 'package:sky/src/widgets/animated_component.dart';
export 'package:sky/src/widgets/animated_container.dart';
export 'package:sky/src/widgets/basic.dart';
export 'package:sky/src/widgets/button_base.dart';
```

There usually isn't a reason to use package: URIs while inside your own package. I believe you could do this instead:

```
export 'src/widgets/animated_component.dart';
export 'src/widgets/animated_container.dart';
export 'src/widgets/basic.dart';
export 'src/widgets/button_base.dart';
```

**Comment by abarth** [comment]
That seems to break `dartdoc`.  It didn't know that `src/widgets/basic.dart` and `package:sky/src/widgets/basic.dart` and got mad if some file imported both because they contain duplicate definitions.

**Comment by sethladd** [comment]
Hm, we need to take a look at that. Where was src/widgets/basic.dart and package:sky/src/widgets/basic.dart both imported into the same file?

**Comment by abarth** [comment]
This was before we created the `src` directory.  Folks had a choice of importing `widgets.dart` or importing individual widgets directly.  The issue wasn't that one file imported both `src/widgets/basic.dart` and `package:sky/src/widgets/basic.dart`.  It was that `widgets.dart` exported `src/widgets/basic.dart` and so anyone who imported `package:sky/widgets.dart` and `package:sky/src/widgets/basic.dart` would have both versions imported.

**Comment by devoncarew** [comment]
That should have been fixed in https://github.com/dart-lang/dartdoc/pull/846 (~2 weeks ago).

**Comment by abarth** [comment]
Oh good.  We fixed it twice.  :)

**Comment by Hixie** [comment]
We also use package:sky/ everywhere because people were copying and pasting code between examples and the framework code and this was resulting in a mixture of styles. By just using package: everywhere we made that a non-issue.

Is there a cost to using package: internally?

**Comment by sethladd** [comment]
> We also use package:sky/ everywhere because people were copying and pasting code between examples and the framework code and this was resulting in a mixture of styles

Ah, yeah, I can see that.

> Is there a cost to using package: internally?

Not that I know of. It was more of an issue of convention of how to import internal libs.

Thanks for the clarification!
