### ISSUE TITLE
publish a new version of `sky`?

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_engine#1099]
What about publishing a new version of `sky`, in order to capture a fix to `sky_tool`? The current published sky_tool doesn't return an error when a `sky_tool start` fails. This makes the UX of launching apps in atom a little cludgey. The current committed sky_tool has a fix for this.

@abarth @iansf

**Comment by abarth** [comment]
Yeah, I've just been waiting for @Hixie to fix #1068.  Maybe we should push now and then push again once he fixed that issue.

**Comment by devoncarew** [comment]
I'll probably publish a new version of the atom plugin ~friday. It'll have code which would prefer the exit code to be correct :)

**Comment by abarth** [comment]
Just pushed Sky v0.0.42

**Comment by devoncarew** [comment]
Great, looks like that captured all the changes I needed:

<img width="962" alt="screen shot 2015-09-09 at 2 58 30 pm" src="https://cloud.githubusercontent.com/assets/1269969/9775373/8603f3c8-5703-11e5-9400-9a760237d6c2.png">

**Comment by abarth** [comment]
\o/
