### ISSUE TITLE
Missing jni.h when building for desktop

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#1122]
I was using the CONTRIBUTING.md instructions (from an existing checkout)

```
./sky/tools/gn
ninja -C out/Debug
```

The build claimed that it could not find `jni.h`

```
In file included from ../../sky/shell/updater/update_task.cc:5:
../../sky/shell/updater/update_task.h:8:10: fatal error: 'jni.h' file not found
#include <jni.h>
```

Possibly related recent change: https://github.com/domokit/sky_engine/commit/29943803773c55b94fad7f3d8e626bb857831a7a

I was able to build successfully when I checked out this commit from last night:
```
commit aecd7e479623774a734c802efeffab65e97f57b0
Author: Adam Barth <github@adambarth.com>
Date:   Wed Sep 9 22:22:58 2015 -0700

    Update README.md
```

**Comment by abarth** [comment]
Yeah, this should be fixed.  It was a transient build error.
