### ISSUE TITLE
Need a way to test SkyShell

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#113]
_From @eseidelGoogle on May 11, 2015 17:39_

SkyShell is our current "shipping" harness for Sky, but right now have no test coverage for it.  Only via mojo_shell on Desktop.

_Copied from original issue: domokit/mojo#156_

**Comment by Hixie** [comment]
@eseidelGoogle Did this change with the recent updates?

**Comment by eseidel** [comment]
Yup. :)  This bug is long dead.
