### ISSUE TITLE
ancestor is Flex assert in widgets/basic.dart

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#1140]
@abarth: https://github.com/domokit/sky_engine/commit/1119f360404fac7e9ceae473c4adf3e9340f4fb2 introduced the assertion 'ancestor is Flex' for Flexible components.

(~line 645 in widgets/basic.dart)

My app fails this assertion when it revisits a certain screen. The reason is that the `ancestor == null`. I think that when these Flexible are removed from the tree, their ancestor is set to null and that when they are recycled, they hit this assertion before receiving their new ancestor.

I was able to fix my app in checked mode by adding `ancestor == null || ancestor is Flex` to the assertion, but I don't think this workaround is the right solution.

This problem may also occur for the `Positioned`, which require that `ancestor is Stack`, but may have null as their ancestor too.

**Comment by abarth** [comment]
Makes sense.  I think the right fix is in

  void syncRenderObject(RenderObjectWrapper old) {

where this function is called.  If we don't find a non-null ancestor, we shouldn't try to validate it.

**Comment by afandria** [comment]
Thanks!

**Comment by Hixie** [comment]
How are they hit before there's an ancestor? That seems suspicious.

**Comment by Hixie** [comment]
Reopening to look at this in more detail.

**Comment by afandria** [comment]
In case it helps, I'll outline what happened in my app. It's likely that there's an easier way to reproduce.

1: Vertical Flex with 3 FlatButton
2: Vertical Flex with 5 FlatButton
3+: Vertical Flex with 1+ Text, 0+ Horizontal Flexes containing 0+ Network Images, and ending with a Horizontal Flex of 4 FlatButton

Eventually, this loops back to screen 1. The crash occurred when going to screen 2.
