### ISSUE TITLE
drag_and_drop.dart needs to use syncConstructorArguments

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#1142]
This one's quick. The drag_and_drop.dart example needs to use `syncConstructorArguments` instead of `syncFields`.

https://github.com/domokit/sky_engine/blob/cf8ddc61b9f4f921d44af783adb365b12b046d2f/examples/widgets/drag_and_drop.dart

**Comment by abarth** [comment]
Thanks!

**Comment by abarth** [comment]
Looks like this is already fixed on master:

https://github.com/domokit/sky_engine/blob/master/examples/widgets/drag_and_drop.dart

**Comment by afandria** [comment]
Whoops, looks like I looking at an old commit.
