### ISSUE TITLE
Setting minWidth, maxWidth, minHeight, and maxHeight

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#1146]
Is it possible to set min/max width/height on widgets, or is it necessary to go into the rendering box layer?

I have a hand of cards and when I move all the cards out, I would like to prevent my Flex's and Stacks' from collapsing to 0 width (or 0 height).

**Comment by abarth** [comment]
You can use a `ConstrainedBox` and pass in a `BoxConstraints` that has those values.

**Comment by afandria** [comment]
That's what I'm looking for, thanks!
