### ISSUE TITLE
Calling setState on two widgets can trigger exception

### ISSUE THREAD

**Issue by abarth** [domokit/sky_engine#1150]
Run the following example:

https://gist.github.com/abarth/0ea4fd11ae20bc19bdc6

Tap the yellow square.  The screen should turn red (with an error widget) and the following exception:

```
I/sky     ( 5479): ------------------------------------------------------------------------
I/sky     ( 5479): Exception caught while syncing build output of Stateful Middle(unkeyed; hashCode=481361675)
I/sky     ( 5479):   old child: Listener(unkeyed; hashCode=718034092)
I/sky     ( 5479):   new child: Listener(unkeyed; hashCode=906789893)
I/sky     ( 5479): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 329 pos 12: 'isFromOldGeneration' is not true.
I/sky     ( 5479): Stack trace:
I/sky     ( 5479): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/sky     ( 5479): #1      Widget._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:329:12)
I/sky     ( 5479): #2      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:867:16)
I/sky     ( 5479): #3      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:931:16)
I/sky     ( 5479): #4      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     ( 5479): #5      TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:573:13)
I/sky     ( 5479): #6      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     ( 5479): #7      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:844:16)
I/sky     ( 5479): #8      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:931:16)
I/sky     ( 5479): #9      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:875:5)
I/sky     ( 5479): #10     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1010:19)
I/sky     ( 5479): #11     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:888:7)
I/sky     ( 5479): #12     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
I/sky     ( 5479): #13     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     ( 5479): Build stack:
I/sky     ( 5479):   Stateful Middle(unkeyed; hashCode=481361675)
I/sky     ( 5479): Current application widget tree:
I/sky     ( 5479): Stateful AppContainer(unkeyed; hashCode=42076679) gen-1
I/sky     ( 5479):  '-RenderViewWrapper(unkeyed; hashCode=686673091) gen-1
I/sky     ( 5479):     '-Stateful Outside(unkeyed; hashCode=406311045) gen-1
I/sky     ( 5479):        '-Stateful Middle(unkeyed; hashCode=481361675) gen-1
I/sky     ( 5479):           '-Listener(unkeyed; hashCode=906789893) gen-2
I/sky     ( 5479):              '-Stateful Inside(unkeyed; hashCode=829207018)
I/sky     ( 5479):                 '-Listener(unkeyed; hashCode=394091859)
I/sky     ( 5479):                    '-Container(unkeyed; hashCode=410978192)
I/sky     ( 5479):                       '-DecoratedBox(unkeyed; hashCode=508027642)
I/sky     ( 5479):                          '-ConstrainedBox(unkeyed; hashCode=166827591)
I/sky     ( 5479): ------------------------------------------------------------------------
```

**Comment by abarth** [comment]
@Hixie @apwilson 

The issue is that both the `Inner` and the `Middle` widget call `setState` during the same frame and are therefore schedule to rebuild.  Because `Inner` was created by `Outer`, it gets to build first.  When it syncs, it is marked as being part of the current generation.  Later, `Middle` rebuilds and when it syncs the assert gets mad because it thinks its child has already been placed somewhere in the tree in this generation (even though the place it goes is in `Middle`.

Probably that assert should allow the case where `newChild` and `oldChild` are the same, but that wasn't sufficient to avoid all the asserts.

**Comment by Hixie** [comment]
Fundamentally in that test the real problem is that Inside gets synced twice, so we do the work for that subtree twice, right? I mean, the assert isn't just bogus here, it's actually catching an issue.

How should we handle the case where we've already done the work for a subtree, only to later find we need to do the work for its parent? Maybe syncChild() should check if newChild is of the new generation, and if so, only do the work if the oldChild is one that would be synced (i.e. canSync and is old generation).

**Comment by Hixie** [comment]
One thing we should definitely do is move the following conditional block to after the old==new block:
```dart
if (oldNode != null && !oldNode.isFromOldGeneration)
      oldNode = null;
```

**Comment by abarth** [comment]
> Fundamentally in that test the real problem is that Inside gets synced twice, so we do the work for that
> subtree twice, right? I mean, the assert isn't just bogus here, it's actually catching an issue.

I'm not sure we do the work for that subtree twice.  The old and new child are the same, so we bail out of syncChild pretty early.

> How should we handle the case where we've already done the work for a subtree, only to later find
> we need to do the work for its parent?

Currently we sort the components that need building by their creation order.  Maybe it would make more sense to sort them by the tree order in the actual widget tree.  Then we'd never arrive in the situation where we need to do work for a parent.

> Maybe syncChild() should check if newChild is of the new generation, and if so, only do the work if the
> oldChild is one that would be synced (i.e. canSync and is old generation).

Maybe we should move this assert after <https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/src/widgets/framework.dart#L400>.  Meaning, first check if the sync is trivial because the new and old child are the same.  That's especially true if we're already the child's parent.  In that case, we're not trying to put this child into two places in the tree....

**Comment by Hixie** [comment]
I have a patch that tries to fix the generation logic to make more sense. Need to test if it fixes the test above.

**Comment by Hixie** [comment]
It doesn't.

**Comment by Hixie** [comment]
I've converted this to a unit test which reproduces the bug, FWIW.

**Comment by Hixie** [comment]
Ok, the fix is just to more aggressively short-circuit the syncChild logic if the children haven't changed.

Patch: #1174
