### ISSUE TITLE
Keyboard displays on launch of SkyDemo.apk

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#116]
_From @eseidelGoogle on May 4, 2015 21:50_

Keyboard displays on launch of SkyDemo.apk

Not sure why. Seems to be a regression since the dart_summit branch was cut. 

Also reported as https://github.com/domokit/sky_sdk/issues/12

_Copied from original issue: domokit/mojo#141_

**Comment by eseidelGoogle** [comment]
This happens every time on the Nexus 10.  I've not seen it on other devices.  Please feel free to take the Nexus 10 from my desk if you'd like to debug!

**Comment by iansf** [comment]
I think it happens on everything that you might consider a tablet, so you
can use a Nexus 7 to repro as well.
