### ISSUE TITLE
SkyDemo.apk v19 is now 12mb

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#134]
v1 (March 18th) was 6.9MB
v11 (June 22nd) was 7.7MB
v15 (July 7th) was 8.9MB
v17 (July 13th) was 12.04MB

I suspect the latest 3mb explosion is due to us including a separate copy of the Sky framework with every .skyx and we probably had a regression in terms of what we're including in said framework.

We could be much smaller than this.

**Comment by eseidelGoogle** [comment]
And v20 is now 16MB!

Something has gone haywire that we just jumped another 4MB.  @abarth

**Comment by eseidelGoogle** [comment]
Part of the growth is that starfield.png inside the game.skyx is 1.5mb alone!   @vlidholt

**Comment by sethladd** [comment]
optipng (or pngcrush) is pretty handy in the build process, to shrink PNGs.

(also, could we use webp ?)

**Comment by Hixie** [comment]
What's the output of `du -ak SkyDemo.apk/ | sort -n` ? (where SkyDemo.apk/ is a directory into which the apk has been decompressed)

**Comment by zanderso** [comment]
23780	/usr/local/google/home/zra/Scratch/SkyDemo.apk/
11304	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets
10784	/usr/local/google/home/zra/Scratch/SkyDemo.apk/lib
10780	/usr/local/google/home/zra/Scratch/SkyDemo.apk/lib/armeabi-v7a
10776	/usr/local/google/home/zra/Scratch/SkyDemo.apk/lib/armeabi-v7a/libsky_shell.so
6124	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/icudtl.dat
3300	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/game.skyx
1576	/usr/local/google/home/zra/Scratch/SkyDemo.apk/classes.dex
612	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/app.skyx
300	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/stocks.skyx
284	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/fitness.skyx
252	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/cards.skyx
232	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/mine_digger.skyx
196	/usr/local/google/home/zra/Scratch/SkyDemo.apk/assets/interactive_flex.skyx
88	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res
28	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xxxhdpi-v4
24	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xxxhdpi-v4/ic_launcher.png
20	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xxhdpi-v4
16	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xxhdpi-v4/ic_launcher.png
16	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xhdpi-v4
16	/usr/local/google/home/zra/Scratch/SkyDemo.apk/META-INF
12	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-xhdpi-v4/ic_launcher.png
12	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-hdpi-v4
8	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-mdpi-v4
8	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-hdpi-v4/ic_launcher.png
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/resources.arsc
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/res/mipmap-mdpi-v4/ic_launcher.png
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/META-INF/MANIFEST.MF
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/META-INF/CHROMIUM.SF
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/META-INF/CHROMIUM.RSA
4	/usr/local/google/home/zra/Scratch/SkyDemo.apk/AndroidManifest.xml

**Comment by abarth** [comment]
It would be interesting to compare these values over time to understand where the growth is coming from.
