### ISSUE TITLE
Stock features to implement once we have Gesture API support

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#144]
_From @Hixie on April 21, 2015 21:29_

- fling sideways to dismiss stock
- long-tap to select stock
- tap to show stock full-screen

Ink splash should be slow while the pointer is down unless long-tap has committed.
The row should highlight while the pointer is down.

_Copied from original issue: domokit/mojo#111_

**Comment by eseidelGoogle** [comment]
I'm not sure this is useful anymore.
