### ISSUE TITLE
OS X specific tar used to publish Sky

### ISSUE THREAD

**Issue by kulakowski** [domokit/sky_engine#160]
The 0.0.19 version of sky uploaded to pub is a tar archive created on OS X. When `pub get`ting it on Linux, this results in many, many error messages like

```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
```

More information about this is found [here](https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt).

**Comment by eseidelGoogle** [comment]
Crazy.  I guess we should disallow running the big_red_button.py from Mac?

@johnmccutchan

**Comment by johnmccutchan** [comment]
@eseidelGoogle Probably want do that for now until we can fix pub.

**Comment by abarth** [comment]
I'm going to mark this as fixed.  I'm working on making releases repeatable, which will prevent this sort of problem from happening again.
