### ISSUE TITLE
Sky 0.0.19 includes all material design icons

### ISSUE THREAD

**Issue by kulakowski** [domokit/sky_engine#161]

**Comment by eseidelGoogle** [comment]
This was unintentional.  They shouldn't include any of them.

Does this cause a problem for you?

**Comment by kulakowski** [comment]
I just found https://github.com/domokit/sky_engine/blob/01ff5c383fc88647c08f11a0d3392238b8bc99de/sky/sdk/lib/assets/.gitignore which should fix it moving forwards.

It does, as currently our packaging format chokes on a directory of that size. I'm happy to close this, given that.

**Comment by abarth** [comment]
Should be fixed in version 21 of the Sky package.
