### ISSUE TITLE
Getting started instructions do not work on a Nexus 5

### ISSUE THREAD

**Issue by wstrange** [domokit/sky_engine#206]
Following https://github.com/domokit/sky_engine/blob/master/sky/sdk/README.md#getting-started-with-sky

On a Nexus 5, with latest lollipop installed, I get this error:

 ./packages/sky/sky_tool start 
Dart VM version: 1.12.0-dev.3.1 (Tue Jul 14 08:45:03 2015) on "macos_x64"
Serving HTTP on 0.0.0.0 port 9888 ...
Starting: Intent { act=android.intent.action.VIEW dat=sky://localhost:9888/lib/main.dart }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=sky://localhost:9888/lib/main.dart flg=0x10000000 }

**Comment by abarth** [comment]
https://github.com/domokit/sky_engine/commit/ce5b798ed9cbbb72a3afa0da54a0d31bd7b64823 should fix the issue.  I'll push the fix in a new Sky package to pub in the morning.

If you want to get this fix before then, you can replace your local copy of sky_tool with the version on master: https://github.com/domokit/sky_engine/blob/master/sky/sdk/lib/sky_tool

**Comment by wstrange** [comment]
Works!  Thanks Adam
