### ISSUE TITLE
Move Dart code from /sky/sdk into the sky_sdk repo

### ISSUE THREAD

**Issue by Scorpiion** [domokit/sky_engine#209]
EDIT: _Old topic was "Transfer Github stars?", changed after updated info from @abarth in comment below._

Hi, would it be possible to somehow transfer the Github stars from the original project?

This original repo has 2027 vs 36 here...
https://github.com/domokit/sky_sdk

I know one can argue that it does not matter really, and I know from a technical point of view it does not. However, for better and worse, the stars does actually mean something in terms of marketing and conversion rates of how many users try out sky later when it's complete. I think it would be a shame to lose these already gained "marketing points".

Maybe it's possible to reach out to Github and ask if they could transfer the stars? Or worse case see if it's possible to transfer all issues from this repo to the old one and then rename that one?

Keep up the good work, cheers!

**Comment by abarth** [comment]
Thanks!  We're actually planning to use the sky_sdk repo to host development of the code that's currently in //sky/sdk.  That's the "main" project that most folks will want to interact with.  This repo will just develop the code in //sky/engine, which is the C++ code that hosts the Dart environments.

**Comment by Scorpiion** [comment]
Ah, okay, that sounds like a great plan! :+1: 

I renamed the issue if you would like to use it for tracking this transfer. If you prefer to track it some other way you can close this issue.

**Comment by abarth** [comment]
We moved this to sky/packages/sky instead.  We'll like to move it to a separate repo eventually, but currently, we want to be able to change the sky package and the sky engine atomically to reduce development friction.

**Comment by Scorpiion** [comment]
Understandable :+1:
