### ISSUE TITLE
Support runtime enabling of strict mode in sky_viewer

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#22]
_From @tonygentilcore on July 16, 2015 14:5_

@abarth and I noticed yesterday that we don't have a mechanism for running sky dart code in strict mode in a release built mojo shell.

The dart content handler enables this via passing `?strict=true`. See:
https://github.com/domokit/mojo/blob/ecf671725e139e27d8e07073e0722d10829e28c7/services/dart/content_handler_main.cc

One way to solve this is to make sky viewer do the same. But if we decide there's a better way to do it for sky, then I'd propose we should also update the dart content handler to match.

/cc @johnmccutchan 

_Copied from original issue: domokit/mojo#327_

**Comment by abarth** [comment]
I started a pull request to use mojo args instead.  That seems better than putting magic into the URLs.
