### ISSUE TITLE
Changing SkyShell.app url requires editing Info.plist

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#251]
Ideally we would be able to load an arbitrary .dart file into SkyShell.app w/o recompiling, like how we can on Android.

**Comment by eseidelGoogle** [comment]
This is even documented in the Wiki as:
iOS doesn't currently support dynamically setting the Sky app to run, so you have to specify the sky_server path you want to launch in the sky/shell/ios/Info.plist file. Find the key org.domokit.sky.load_url and set the value to the sky_server URL of the app you would like to run, for example http://localhost:8080/sky/sdk/example/stocks/lib/main.dart.

**Comment by iansf** [comment]
Fixed by https://github.com/domokit/sky_engine/pull/260
