### ISSUE TITLE
iOS should share a similar sky_tool/shelldb workflow with Android

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#255]
We can change the Android workflow to better mesh with iOS.  But we don't want 2 completely separate workflows.

Something like shelldb start should work on iOS?

**Comment by eseidelGoogle** [comment]
Right now the wiki directs you to use:
build/config/ios/ios_sim.py -p out/ios_sim_Debug/Sky.app debug

Which is fine.  We should probably just have sky_tool call that for the developer.

**Comment by eseidelGoogle** [comment]
Specifically @collinjackson is going to need:
`shelldb start path/to/main.dart` to work for his demos next week.

**Comment by eseidelGoogle** [comment]
I started down this path in https://github.com/eseidelGoogle/sky_engine/tree/shelldb_mac.  it's not clear that it's worth abstracting shelldb.  We definitely want a unified workflow, but maybe we don't need one for Collin's demo.

**Comment by eseidelGoogle** [comment]
@iansf is working on something like this I believe?

**Comment by iansf** [comment]
Yes

**Comment by iansf** [comment]
I think this is reasonably closed by my recent work on sky_tools.  Remaining differences can be tracked by separate tickets.
