### ISSUE TITLE
Should not have to launch SkyShell.app inside lldb

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#256]
Should be able to launch it in Release mode, etc inside the simulator w/o using a debugger.

@chinmaygarde

**Comment by eseidelGoogle** [comment]
Nevermind, I was confused.

**Comment by iansf** [comment]
Running something like the following:

`build/config/ios/ios_sim.py -p out/ios_sim_Debug/Sky.app -t sky/sdk/example/stocks/lib/main.dart launch`

results in a black screen and the following log output:
```
Jul 23 17:02:23 iansf-macpro assertiond[97157]: assertion failed: 14E46 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
Jul 23 17:02:23 iansf-macpro.roam.corp.google.com SpringBoard[97153]: LICreateIconForImage passed NULL CGImageRef image
Jul 23 17:02:23 iansf-macpro Sky[54124]: assertion failed: 14E46 12F69: libxpc.dylib + 59338 [23DBFC52-1ABE-3A33-8FE2-637C3B0EA394]: 0x7d
Jul 23 17:02:23 iansf-macpro assertiond[97157]: assertion failed: 14E46 12F69: assertiond + 12334 [8E465C14-E4AE-36E9-AFBE-D28459602962]: 0x1
```
whereas running:

`build/config/ios/ios_sim.py -p out/ios_sim_Debug/Sky.app -t sky/sdk/example/stocks/lib/main.dart debug`

works fine.
