### ISSUE TITLE
Stacked Positioned appears to fail with left,right,top,bottom: 0.0

### ISSUE THREAD

**Issue by HansMuller** [domokit/sky_engine#275]
The following example is mostly just card_collection.dart.  List items are Stacks with two children: a fixed height Card and a  Positioned item with a green Container child.  Expected result is the green background appearing around the edges of the Cards.

The Positioned item is expected to have the same size as the Card and Stack.  If top,left:0.0 are specified it does, if top,left,right,bottom:.0.0 are specified then it vanishes. Presumably, it's 0x0 in that case.

https://github.com/HansMuller/sky_engine/blob/positioned-test-case/sky/sdk/example/widgets/test_case.dart

Uncomment the lines here to see the failure mode.
https://github.com/HansMuller/sky_engine/blob/positioned-test-case/sky/sdk/example/widgets/test_case.dart#L68

**Comment by abarth** [comment]
Great but.  The stack layout algorithm was just wrong.  :)

**Comment by abarth** [comment]
s/but/bug/
