### ISSUE TITLE
Animate drawer closing when transitioning to the Settings menu in Stocks

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#32]
_From @iansf on July 7, 2015 22:22_

_Copied from original issue: domokit/mojo#306_

**Comment by Hixie** [comment]
_From @collinjackson on July 8, 2015 0:41_

The drawer animation is actually starting, you just can't see it because the Settings transition animation isn't implemented yet.

**Comment by collinjackson** [comment]
Fixed in 881addf5d24b6bebb74c6c0d1b07cf6915c8695f
