### ISSUE TITLE
Never loads on the M preview

### ISSUE THREAD

**Issue by jgw96** [domokit/sky_engine#336]
Crashes on load on the M Dev preview update. Running this on a Nexus 6. Screen starts black and then crashes.

**Comment by eseidelGoogle** [comment]
@Hixie was using an M preview for a while.  I'm not sure if he was using the official Dev preview or not.

**Comment by jgw96** [comment]
@eseidelGoogle wish I had more info for you but I'm used to my chrome Dev tools (; not so much on debugging android apps.

**Comment by abarth** [comment]
I wonder if this is fixed by the new way of creating the GL interface for Skia.  We should try again after the next release.

**Comment by abarth** [comment]
@jgw96 Would you be willing to try this again now that Sky 0.0.24 has been released?  You should be able to upgrade your version of Sky by running `pub upgrade` in the same directory as your `pubspec.yaml` file.

**Comment by jgw96** [comment]
@abarth sorry I may have submitted this issue in the wrong repository. I encountered this issue when trying the sky demo app available in the play store. I don't have sky setup on any of my machines. Although I could if needed?

**Comment by abarth** [comment]
Ah, that makes sense.  We should update the Sky Demo app in the play store.  We'll do that today.  Thanks!

**Comment by jgw96** [comment]
@abarth. No problem! Love the work you guys are doing! We use a lot of phonegap at work but I would love to be able to use something like sky instead.

**Comment by abarth** [comment]
@eseidelGoogle published a new version of the APK today.  It might be worth trying again with v21.

**Comment by abarth** [comment]
I believe this will be fixed in v22 by 3e7ab3a338b413bdde1ea2d7cf68f869106f1520

**Comment by jgw96** [comment]
@abarth currently downloading to test, sorry have been very busy lately.

**Comment by abarth** [comment]
No worries.  We haven't published the version with the fix yet.  We'll probably publish it later this week.
