### ISSUE TITLE
dart:io support

### ISSUE THREAD

**Issue by kaendfinger** [domokit/sky_engine#350]
It looks like the `dart:io` natives are hooked up correctly.

```
➜ AndroidDsaViewer /Applications/SkyShell.app/Contents/MacOS/SkyShell --package-root=packages lib/main.dart
#READY
#BEGIN
[ERROR:dart_error.cc(19)] 'dart:io-patch/file_patch.dart': error: line 6: native function 'File_Exists' (1 arguments) cannot be found
  static _exists(String path) native "File_Exists";
```

**Comment by eseidelGoogle** [comment]
This may be an issue specific to Mac.  Was this a specific dart:io call, or any dart:io call whcih triggered this?

**Comment by kaendfinger** [comment]
@eseidelGoogle I'm actually getting this on Android as well. The filesystem calls are what I am using atm, but I suspect that it's an all or nothing.

**Comment by eseidelGoogle** [comment]
We have enough of dart:io (care of @johnmccutchan) to support Observatory, but I suspect our embedding is missing some pieces yes.

**Comment by johnmccutchan** [comment]
Hi,

Currently file system operations aren't hooked up. All network related operations are fully supported.

Enabling file system won't be too much work.

**Comment by kaendfinger** [comment]
@johnmccutchan Awesome.

**Comment by abarth** [comment]
@johnmccutchan Can you point me where to start hooking up file operations?

**Comment by johnmccutchan** [comment]
@abarth The change is actually in the VM, I've put up a [CL](https://codereview.chromium.org/1265703004/).

**Comment by johnmccutchan** [comment]
CL has landed. Next roll of Dart will fix this.

**Comment by abarth** [comment]
Thanks!

**Comment by kaendfinger** [comment]
:+1:
