### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by jimbeveridge** [domokit/sky_engine#356]
On https://github.com/domokit/sky_engine, the link to Getting started with Sky is 404.

On https://github.com/domokit/sky_engine/tree/master/sky, the links at the bottom to the Sky SDK and the skd/lib directory are 404.

On https://github.com/domokit/sky_engine/tree/master/sky/packages/sky, the link to the widgets tutorial is 404.

**Comment by jimbeveridge** [comment]
The "Getting started" link and the "widgets tutorial" link appear okay now, but the other two are still 404.

**Comment by abarth** [comment]
I think I've fixed these now.  Please re-open if I missed any.  Thanks!
