### ISSUE TITLE
Move headline Sky examples out of the Sky package

### ISSUE THREAD

**Issue by abarth** [domokit/sky_engine#407]
Currently all our examples are inside the Sky package, which is convenient for development but makes them harder for people to use as templates.  Instead, we should move the "headline" examples (e.g., stocks, game, and fitness) out into their own packages so they're examples of stand-alone uses of Sky.

**Comment by sethladd** [comment]
:+1:

**Comment by abarth** [comment]
@iansf did this in 2a697e2cd468c788aaf8100237a0e1683fce113a
