### ISSUE TITLE
Stacked Positioned is not re-rendered, when its position changes

### ISSUE THREAD

**Issue by turu** [domokit/sky_engine#408]
**The scenario is this**: I have a StatefulComponent, which builds a Stack of several Positioned Components, with SizeObserver placed around the Stack. 

Position of widgets from the stack is calculated using the size of their parent, stateful widget. Hence, when the resize callback fires, the stateful widget is marked to be rebuilt and the new size is saved. It is then passed to positioned widgets upon next build, so that they can place themselves correctly on the screen.

The issue is that if position is _the only_ thing that changed down the widget tree, nothing gets re-rendered in the end.

**See a narrowed down example** at: https://gist.github.com/turu/7ccd9287209f96df881e

Uncomment line 10 to see the failure mode. Everything gets rendered correctly as long as something else apart from the position changes as well (text label in the example).

**Expected result**: Stacked Positioned is always re-rendered, when its position is the only thing that changed.

**Actual result**: After widget tree is rendered and the resize callback fires for the first time, the fact that position changed is ignored and the component is not re-rendered. As a result f.e., when you start to rotate the screen, you are stuck one rotation behind.

**Comment by abarth** [comment]
Thanks for the report.  Investigating.

**Comment by abarth** [comment]
I have the repro.
