### ISSUE TITLE
widgets tutorial link on pub readme is broken

### ISSUE THREAD

**Issue by robbishop65** [domokit/sky_engine#417]
Error 404 Not Found
The path '/packages/lib/widgets/README.md' was not found.

Edit:  documentation link broken too: http://www.dartdocs.org/documentation/sky/0.0.26/index.html#sky

**Comment by abarth** [comment]
Thanks!  Will fix.

**Comment by abarth** [comment]
The version on pub should be fixed next time we make a release (typically weekly).
