### ISSUE TITLE
Show a basic graph in Fitness App

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#467]
Doesn't need to use https://github.com/google/charted yet, but we need some extremely basic graphing for the Fitness app 0.1

**Comment by eseidelGoogle** [comment]
More advanced charting covered by https://github.com/domokit/sky_engine/issues/59

Is this something that interests you @chinmaygarde ?

**Comment by collinjackson** [comment]
Basic chart is showing, I'm working on improving it
