### ISSUE TITLE
widgets README example out of date

### ISSUE THREAD

**Issue by RiaJ** [domokit/sky_engine#490]
"new Image(src: 'search.png', size: const Size(25.0, 25.0))" in the second example. Image doesn't take src or size.

**Comment by abarth** [comment]
Thanks!  Should be fixed in febedf0ffe13b429a9b16385e1197b8d9b1e595b

**Comment by RiaJ** [comment]
NetworkImage takes width and height?

**Comment by abarth** [comment]
Very true: 012e7068d9bba953ae745f2c8118f022e8d8ed6e

What else did I miss?  :)

**Comment by RiaJ** [comment]
Can't find anything else :)
