### ISSUE TITLE
sky_tool start fails to start sky_server if sky_tools isn't a dependency

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#539]
It should at least fail hard.  Right now it just logs and continues:

```
Package "sky_tools" is not an immediate dependency.
Cannot run executables in transitive dependencies.
```

**Comment by eseidelGoogle** [comment]
I believe I created this project using sky_tools init, so presumably that template should be updated to include this direct dependency.

**Comment by iansf** [comment]
I can't repro this.  Removing sky_tools from the Stocks example pubspec.yaml seems to work fine for me.  Please reopen if this is still an issue.
