### ISSUE TITLE
Sky misses methods for converting points to local space

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#56]
_From @vlidholt on June 17, 2015 21:15_

In the handleEvent method of RenderBox the BoxHitTestEntry provides a local point for the pointerdown event. But for dragged pointers there is no way of finding the local coordinates within the box. The dragged delta is in global space and therefore doesn't solve the problem.

A method that converts to and from the global space would be useful. E.g.
`Point convertPointToLocalSpace(Point point)` that is a method of RenderBox (or one of its super classes). Another solution could be to pass down the local point in the event method. 

_Copied from original issue: domokit/mojo#249_

**Comment by Hixie** [comment]
We should probably be able to convert from the coordinate system of any box to the coordinate system of any other box in the same tree.

It would be useful if specific use cases were listed in this bug so we can make sure to support them well.

**Comment by abarth** [comment]
These methods exist now: `localToGlobal` and `globalToLocal`
