### ISSUE TITLE
Use Dart unittest runner instead of test_sky

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#581]
Ideally Sky should use Dart's unittest runner instead of the one we inherited from Blink.

https://pub.dartlang.org/packages/test_runner

We could use this with our own `--dart-bin` however currently `sky_shell` when run with `--non-interactive` does not follow the same exit criteria as test_runner expects from `dart`.

`dart` exits when `main` is complete and all work spun off from main is resolved.  We could do the same in `sky_shell` but we need to type some code to do so.

**Comment by devoncarew** [comment]
I believe `test_runner` is not generally used. We'll probably want to figure out a way to integrate with `test`. It has built in platform selectors (@TestOn('vm') - https://pub.dartlang.org/packages/test), but I don't know if we could add our own platform selectors and how to tell `test` to run using a different executable (`sky_shell`).

@sethladd @nex3 @kevmoo

**Comment by kevmoo** [comment]
Love it!

We've planned to support other platforms, but we don't have a mechanism defined (yet) for it.

1. Open an issue on pkg/test requesting extensible platforms
2. Gives us a doc/gist/something describing your desired behavior. How would you like it to work? What would a test file look like for sky? What commands would it need to run? Assuming `sky_shell` can do some sort of IPC (websockets, http, etc) it should look a lot like how we support browsers + dart2js now.

**Comment by zoechi** [comment]
Some issues that might be related
- dart-lang/test#109
- dart-lang/test#99
- dart-lang/test#49

**Comment by abarth** [comment]
I started working on this issue in https://github.com/dart-lang/test/pull/320

**Comment by abarth** [comment]
Fixed in https://github.com/domokit/sky_engine/commit/1133c5c0efd8da35daf7884e993b2d46410790a2
