### ISSUE TITLE
sky_tool should enforce a minimum version for pub

### ISSUE THREAD

**Issue by abarth** [domokit/sky_engine#582]
If you run with an old version of pub, sky_tool will leave an orphan sky_server.

I'm not sure what minimum version to require...  Maybe 1.11?

/cc @iansf @MitchRudominer

**Comment by eseidelGoogle** [comment]
1.11 is the first one with sdk_ext support, so we shouldn't support anything below that.  We can specify that in our pubspec.yaml:

https://www.dartlang.org/tools/pub/pubspec.html
```
environment:
  sdk: ">=1.11.0"
```

**Comment by eseidelGoogle** [comment]
I believe https://github.com/domokit/sky_engine/pull/586 should fix this.
