### ISSUE TITLE
Need a Keyboard Service on iOS

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#609]
Fitness, Stocks and AddressBook all use the Input widget which depends on the Keyboard Service.  Fitness is the only one of those which requests a numeric keyboard instead of the default text keyboard.

iOS has no implementation of the Keyboard service yet, but we'll need one.

We may need to change the current Keyboard.mojom design to accomidate iOS.  Unfortuantely that file is currently in the mojo repository as well as both of its current implementations (one in C++ and one in Java).

@chinmaygarde has kindly volunteered to take a stab at this.

This bug blocks @collinjackson from being able to carry the Fitness app on his iPhone. :)

**Comment by chinmaygarde** [comment]
Fixed by https://github.com/domokit/sky_engine/pull/628
