### ISSUE TITLE
Add Drag/Drop event

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#612]
I'm creating a card game where certain cards can be dragged from the player's hand and dropped into a discard pile.

Currently, the Widget's Listener doesn't expose an `onDrop` event, which would be helpful for my scenario. Please add this feature. (The alternative, keeping track of all drawn item positions and computing an overlap `onPointerUp` seems like too much work for those Widgets/Components.)

In addition to `onDrop`, it may be helpful to add `onDragOver` (when hovering over an onDrop target), `onDragStart`, and `onDragEnd`.

**Comment by abarth** [comment]
Most of the code is in https://github.com/domokit/sky_engine/pull/627  I still need to make an example and some tests to show that it works.

**Comment by afandria** [comment]
Awesome, thanks!
