### ISSUE TITLE
seeing pub failures due to material_design_icons

### ISSUE THREAD

**Issue by devoncarew** [domokit/sky_engine#633]
When running pub get on a newly created sky project, I see pub failures:

```
Downloading material_design_icons 0.0.2...
Timed out after 30.0s while downloading https://pub.dartlang.org/packages/material_design_icons/versions/0.0.2.tar.gz.
This is likely a transient error. Please try again later.
```

The download for the material_design_icons pub package fails several times in a row. This is for a 1.11.1 SDK. The package's archive is 30.5 MB, and the download time for me exceeds the 30 sec timeout. We should probably reduce the size of the package. (not sure if this would fail on a 1.12.0 SDK)

**Comment by devoncarew** [comment]
I was able to download a few minutes later with `1.11.3`. Still, it's probably worth seeing if there's an easy way to put the package on a diet.

**Comment by sethladd** [comment]
Apparently the timeout is removed in 1.12

**Comment by abarth** [comment]
Sounds like "won't fix" ?  We also have the material design icons in a tarball on Google storage and could download it separately from `pub` if necessary.

**Comment by devoncarew** [comment]
It doesn't look like there's an single large file(s) in the package. It's large because it contains 85k items (and uncompresses to 300MB).

We're not seeing the hit to `pub get` or `pub update` because we already have the package in our pub_cache. But first time users will see a delay the first time the run `pub get` on a sky project, or activate the `sky_tools` tool. It would be nice to keep these operations fast.

**Comment by abarth** [comment]
We can also strip down the number of files we put in the package.  We can remove all the SVGs, for example.

**Comment by abarth** [comment]
I just pushed a new version of material_design_icons that is 16M.  I'm going to close this issue.  If we need to shrink more, please re-open this issue.
