### ISSUE TITLE
iOS no longer builds

### ISSUE THREAD

**Issue by iansf** [domokit/sky_engine#642]
ninja -C out/ios_Release -j 512 gives the following (as does ios_Debug):

CXX obj/dart/runtime/vm/libdart_vm/profiler.o
FAILED: /Users/iansf/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/dart/runtime/vm/libdart_vm/profiler.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DDONT_EMBED_BUILD_METADATA -DNO_TCMALLOC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DDISABLE_FTP_SUPPORT=1 -DDISABLE_NACL -DENABLE_CONFIGURATION_POLICY -DV8_USE_EXTERNAL_STARTUP_DATA -DCHROMIUM_BUILD -DCR_CLANG_REVISION=241602-3 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNDEBUG -I../../dart/runtime -I../.. -Igen -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -miphoneos-version-min=7.0 -fno-strict-aliasing -arch arm64 -fcolor-diagnostics -Wall -Wsign-compare -Wendif-labels -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-char-subscripts -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-reserved-user-defined-literal -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Os -fno-ident -fdata-sections -ffunction-sections -g2 -Werror -Wall -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -Wvla -Wno-conversion-null -Woverloaded-virtual -g3 -ggdb3 -fno-rtti -fno-exceptions -O3 -fno-threadsafe-statics -fvisibility-inlines-hidden -std=c++11 -fno-rtti -fno-exceptions -c ../../dart/runtime/vm/profiler.cc -o obj/dart/runtime/vm/libdart_vm/profiler.o
../../dart/runtime/vm/profiler.cc:984:5: error: unknown token in expression
    COPY_FP_REGISTER(fp);
    ^
../../dart/runtime/vm/globals.h:114:44: note: expanded from macro 'COPY_FP_REGISTER'
#define COPY_FP_REGISTER(fp) asm volatile ("mov %0, %%x29" : "=r" (fp) );
                                           ^
<inline asm>:1:11: note: instantiated into assembly here
        mov x24, %x29
                 ^
../../dart/runtime/vm/profiler.cc:984:5: error: invalid operand
    COPY_FP_REGISTER(fp);
    ^
../../dart/runtime/vm/globals.h:114:44: note: expanded from macro 'COPY_FP_REGISTER'
#define COPY_FP_REGISTER(fp) asm volatile ("mov %0, %%x29" : "=r" (fp) );
                                           ^
<inline asm>:1:11: note: instantiated into assembly here
        mov x24, %x29
                 ^
2 errors generated.

**Comment by iansf** [comment]
@chinmaygarde in case you know something about this.

**Comment by chinmaygarde** [comment]
Looking at it now

**Comment by chinmaygarde** [comment]
https://github.com/domokit/sky_engine/pull/655
