### ISSUE TITLE
Transform doesn't transform constraints

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#699]
Here are some screenshots:
![screenshot_2015-08-19-13-27-25](https://cloud.githubusercontent.com/assets/2432033/9368193/b77335d8-4676-11e5-8a28-a01a3bbb01c1.png)
![screenshot aug 19 2015 1-30-07 pm](https://cloud.githubusercontent.com/assets/2432033/9368192/b773390c-4676-11e5-8f32-844579564883.png)

For simplicity, I'm only showing the code for a single row of my setup:

```
new Transform(
  transform: new Matrix4.identity().scale(0.5, 0.5),
  child: new Flex(aListOfNetworkImages)
)
```

The Flex of NetworkImage is actually too long to show up on the screen normally (13 cards), so it gets cut off after about 5 images (portrait) or 9 (landscape). I applied the scale so that I could see more cards, but it seems that Sky doesn't actually draw pixels it "thinks" are off-screen. The bug is that what is considered to be off-screen is incorrect.

**Comment by afandria** [comment]
Here's what it looks like, if instead of transforming there, I scale down each card on its own.

![screenshot aug 19 2015 1-40-16 pm](https://cloud.githubusercontent.com/assets/2432033/9368408/f9530356-4677-11e5-9faf-881f6d79b022.png)
![screenshot_2015-08-19-13-41-52](https://cloud.githubusercontent.com/assets/2432033/9368431/246602b4-4678-11e5-91b3-b89f419b496f.png)


Unfortunately, there are huge gaps, which makes me think that Component/Widget scaling is not accounted for in Sky.

**Comment by Hixie** [comment]
Transform needs to adjust the constraints it passes to its child. @abarth

**Comment by abarth** [comment]
I guess I'm wondering whether Transform makes sense for what you're trying to do here.  Why not just use the Flex to set the width of the images (i.e., using Flexible) and then leave the height to be determined by the NetworkImage?  It should scale the image to the proper size.

**Comment by afandria** [comment]
I didn't know about Flexible, but it does automatically resize the images if I don't pick a manual width/height. It may be just my inexperience with Widgets, but I thought Transform would be fine to use to resize my objects manually.

(I will eventually want the cards to overlap (will try Stack and Positioned). I was using Flex here just to start out when I noticed this issue with Transform.)

**Comment by abarth** [comment]
@afandria The fancy image-resizing logic is new in v0.0.34 of the Sky package.

Transform is intended to be a paint-time operation, which is why it doesn't affect layout.  For example, if you had all the cards arranged on the table and then wanted to add some perspective or spin the table around, that would be use case for Transform.

**Comment by abarth** [comment]
I think this is now working for @afandria .  Please re-open if there's something you'd still like changed.
