### ISSUE TITLE
Shadows get clipped in certain situations

### ISSUE THREAD

**Issue by apwilson** [domokit/sky_engine#738]
I have a container.  This container holds a horizontal flex of components that have shadows.

When the horizontal Flex's width is less than that of the container everything is fine (only one or two items in the flex in my example).  As soon as the flex's width exceeds the container's width (three or more in the flex in my example), the components' shadows get clipped on the top (and maybe bottoms as well).

**Comment by Hixie** [comment]
Yeah, that makes sense. CC @abarth.

**Comment by Hixie** [comment]
I spoke with @apwilson about this. I think our conclusion was that this is working as intended. When you use Flex, the contract is that you'll give the Flex enough room to contain its children; if you don't, then we enter an emergency mode where we clip to prevent overflow everywhere.

I'm going to make this more obvious by asserting in checked mode, as part of a wider set of changes to flex.

**Comment by Hixie** [comment]
I made Flex paint red at its overflow edge when it has overflow.
