### ISSUE TITLE
!_size.isInfinite assertion is non-actionable

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#744]
I don't know how to fix it when I get one:

I/sky     (29395): Exception raised during layout:
I/sky     (29395): 'http://localhost:9888/packages/sky/rendering/box.dart': Failed assertion: line 322 pos 12: '!_size.isInfinite' is not true.
I/sky     (29395): Context:
I/sky     (29395): RenderView NEEDS-LAYOUT
I/sky     (29395):   parentData: null
I/sky     (29395):   constraints: null
I/sky     (29395):   child: RenderStack NEEDS-LAYOUT
I/sky     (29395):     parentData: <none>
I/sky     (29395):     constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     (29395):     size: Size(0.0, 0.0)
I/sky     (29395):     child 1: RenderScaffold NEEDS-LAYOUT
I/sky     (29395):       parentData: position=Point(0.0, 0.0); top=null; right=null; bottom=null, left=null
I/sky     (29395):       constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     (29395):       size: Size(360.0, 592.0)
I/sky     (29395):       ScaffoldSlots.body: RenderDecoratedBox NEEDS-LAYOUT
I/sky     (29395):         parentData: position=Point(0.0, 0.0)
I/sky     (29395):         constraints: BoxConstraints(360.0<=w<360.0, 511.0<=h<511.0)
I/sky     (29395):         size: Size(0.0, 0.0)
I/sky     (29395):         decoration:
I/sky     (29395):           backgroundColor: Color(0xff424242)
I/sky     (29395):           borderRadius: 2.0
I/sky     (29395):         child: RenderSizeObserver NEEDS-LAYOUT
I/sky     (29395):           parentData: position=Point(0.0, 0.0)

We need to make the assertion much easier to understand.  Probably by making the log much better.

@Hixie

**Comment by eseidelGoogle** [comment]
Turns out I had a Positioned element in a Stack, which recently became infinite.  @abarth.  but this bug still stands that this assert is super confusing.

**Comment by Hixie** [comment]
Fundamentally this assert fires when you are using a render object that wants to fill its parent in a render object that expects its children to shrink-wrap.

You see this a lot when using Flex (expands to fit parent, then positions children in that space) in a Scrollable (has infinite internal size).

I am approaching this issue from multiple directions.
- [ ] Make Flex support both being in a parent that has a fixed size and one that has infinite internal size.
- [ ] Make the assert itself clearer about what is going on.
- [ ] Add comments at the assert site explaining this (basically what I talk about above).
- [ ] See what I can do about making the error message itself better. Maybe by trying to catch the exception closer to the fail site (e.g. add a try-catch block to layout(), like we have in layoutWithoutResize()). This might have perf implications so I'll have to check this carefully.

Any other ideas?

**Comment by Hixie** [comment]
This is much more actionable now, though still not perfect. If you hit this again, file a new bug.
