### ISSUE TITLE
DrawerItem, DrawerHeader should take a child instead of children

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#755]
These are some of the oldest components in sky which now need a bit of a refresh.

@abarth @Hixie

**Comment by eseidel** [comment]
@Hixie I'm not sure.  They'd probably just be the same class with one argument changed?  Unless the logic is somehow different between them?  The default is just not always obvious in my memory.

**Comment by Hixie** [comment]
Flex is a ten-line wrapper around RenderFlex. It has basically no logic except passing the arguments on through to RenderFlex. What I'm proposing is having two wrappers for RenderFlex, maybe FlexH and FlexV, so instead of specifying the direction as an argument (and having to remember the default), you just specify the one you want.

**Comment by eseidel** [comment]
That actually sounds like a good idea.  Makes it explicit and much shorter.  Then FlexH (or whichever one is not-default at the moment) is not a second-class citizen.  Does that mean we need BlockH and BlockV too then?  @abarth

**Comment by abarth** [comment]
Maybe `Row` and `Col` to give them short, snappy names?

After @Hixie's three-step plan, you should almost never use `Block`.  If you want something scrollable, you'll probably use `ScrollableList<T>`, which had a `scrollDirection` that defaults to vertical.

**Comment by eseidel** [comment]
ScrollableRow<T> ScrollableCol<T> ?  It's not clear to me that one default makes more sense over the other.  But I also feel like we're splitting hairs here.

**Comment by Hixie** [comment]
I haven't seen many horizontal scrollable widgets in practice so far, except pageable, which should just default to horizontal. But if it having both directions for scrollables becomes as common as for flexes, then sure, we can have subclasses for each direction there too.

Filed #770 for Row / Column. (I don't think we need to abbreviate Column, it's pretty short already. We generally have been good about avoiding arbitrary abbreviations so far.)

**Comment by eseidelGoogle** [comment]
Pageable. Tab strip. And the new wheel of fortune widgets @HansMuller is
working on are all horizontal scrollable. But yeah I don't know the
relative frequency.
