### ISSUE TITLE
Add NetworkFile

### ISSUE THREAD

**Issue by afandria** [domokit/sky_engine#758]
I saw that NetworkImage uses [image_cache.dart](https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/mojo/net/image_cache.dart) and [fetch.dart](https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/mojo/net/fetch.dart) to resolve the url and create a ResourceImage.

Is the same url fetching/resolving technique useful to access local (or remote) files in a Sky app? (For example fetching text files or json strings.) If so, it may be worth adding NetworkFile to complement NetworkImage.

**Comment by abarth** [comment]
Can you explain a bit more what you're trying to accomplish?  If you want to read and write local files, you can use the `dart:io` package.  If you want to fetch remote files from a web server, you can use the `fetch.dart` library.

**Comment by afandria** [comment]
I may have used the wrong words. I know that `dart:io File` allows access to the local filesystem, but I was instead referring to the files served on localhost when running sky_shell.

The widgets example includes `NetworkImage(src: "menu.png")`, which I discovered resolved to the `lib` folder of the project. (The files in the `lib` directory is what I am referring to as local.)

Since it's possible to access image files in `lib` with `NetworkImage`, I thought it would be appropriate to have `NetworkFile` to complement it for non-image files.

**Comment by abarth** [comment]
It's not clear to me what `NetworkFile` would do.  For images, `NetworkImage` fetches the image and then draws the image at that location in the widget tree.  For arbitrary files, it's unclear what visual presentation they would have.

If you just want to read the contents of the files, you can use `fetch.dart.  For example, you wanted to read the contents of `foo.txt` in the `lib` directory, you could call `fetchString('foo.txt')`.

**Comment by afandria** [comment]
You're right. I didn't see `fetchString`; that is exactly what I want.
