### ISSUE TITLE
Text wrapping/alignment doesn't survive resize (portrait to landscape mode)

### ISSUE THREAD

**Issue by apwilson** [domokit/sky_engine#760]
I'm finding if my text is nicely aligned right and spans multiple lines (due to wrapping) in portrait mode it will draw partially offscreen in landscape mode.

**Comment by apwilson** [comment]
This seems to be related to word wrapping - if I happen to wrap in the landscape mode everything lines up fine.  If I don't - the text is on a single line - the text goes offscreen.

**Comment by abarth** [comment]
Discussed with @apwilson and we weren't sure how to reproduce the issue.  Please re-open if this happens again.
