### ISSUE TITLE
global key error while using fitness app

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#803]
```
E/chromium(31048): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(31048): Concurrent modification during iteration: Instance of '_CompactLinkedHashSet<GlobalKeyRemoveListener>'.
E/chromium(31048): #0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:409)
E/chromium(31048): #1      GlobalKey._notifyListeners (/src/sky_engine/src/examples/fitness/packages/sky/widgets/framework.dart:168)
E/chromium(31048): #2      Widget._notifyMountStatusChanged (/src/sky_engine/src/examples/fitness/packages/sky/widgets/framework.dart:281)
E/chromium(31048): #3      _buildDirtyComponents (/src/sky_engine/src/examples/fitness/packages/sky/widgets/framework.dart:898)
E/chromium(31048): #4      Component.flushBuild (/src/sky_engine/src/examples/fitness/packages/sky/widgets/framework.dart:755)
E/chromium(31048): #5      WidgetSkyBinding.beginFrame (/src/sky_engine/src/examples/fitness/packages/sky/widgets/framework.dart:1309)
E/chromium(31048): #6      _beginFrame (/src/sky_engine/src/examples/fitness/packages/sky/base/scheduler.dart:30)
D/Finsky  (29147): [1] 5.onFinished: Installation state replication succeeded.
```

@abarth

**Comment by eseidelGoogle** [comment]
Built from c7023bd28cd5598745b90f1309b9e784df4b2715

**Comment by abarth** [comment]
How do you trigger this error?

**Comment by eseidelGoogle** [comment]
Adding a measurement seems to?

**Comment by eseidelGoogle** [comment]
1.  `cd examples/fitness`
2. ` pub get`
3. `adb logcat -c && ./packages/sky/sky_tool start --checked && adb logcat`
4. Click plus button
5. Hit "add" button to add a measurement.
6.  Type 25.
7.  Click "Save" in upper right corner.

Console:
``I/sky     ( 2105): Saving to /data/data/org.domokit.sky.shell/cache/data.json
I/sky     ( 2105): Success! File: '/data/data/org.domokit.sky.shell/cache/data.json'
E/chromium( 2105): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium( 2105): 'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 131 pos 12: '!_notifyingListeners' is not true.
E/chromium( 2105): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium( 2105): #1      GlobalKey.unregisterRemoveListener (http://localhost:9888/packages/sky/widgets/framework.dart:131:12)
E/chromium( 2105): #2      Focus._updateWidgetRemovalListener (http://localhost:9888/packages/sky/widgets/focus.dart:118:19)
E/chromium( 2105): #3      Focus._handleWidgetRemoved (http://localhost:9888/packages/sky/widgets/focus.dart:109:5)
E/chromium( 2105): #4      GlobalKey._notifyListeners (http://localhost:9888/packages/sky/widgets/framework.dart:169:21)
E/chromium( 2105): #5      Widget._notifyMountStatusChanged (http://localhost:9888/packages/sky/widgets/framework.dart:281:15)
E/chromium( 2105): #6      _buildDirtyComponents (http://localhost:9888/packages/sky/widgets/framework.dart:898:12)
E/chromium( 2105): #7      Component.flushBuild (http://localhost:9888/packages/sky/widgets/framework.dart:755:7)
E/chromium( 2105): #8      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1309:15)
E/chromium( 2105): #9      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium( 2105): [ERROR:dart_error.cc(28)] #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium( 2105): #1      GlobalKey.unregisterRemoveListener (http://localhost:9888/packages/sky/widgets/framework.dart:131:12)
E/chromium( 2105): #2      Focus._updateWidgetRemovalListener (http://localhost:9888/packages/sky/widgets/focus.dart:118:19)
E/chromium( 2105): #3      Focus._handleWidgetRemoved (http://localhost:9888/packages/sky/widgets/focus.dart:109:5)
E/chromium( 2105): #4      GlobalKey._notifyListeners (http://localhost:9888/packages/sky/widgets/framework.dart:169:21)
E/chromium( 2105): #5      Widget._notifyMountStatusChanged (http://localhost:9888/packages/sky/widgets/framework.dart:281:15)
E/chromium( 2105): #6      _buildDirtyComponents (http://localhost:9888/packages/sky/widgets/framework.dart:898:12)
E/chromium( 2105): #7      Component.flushBuild (http://localhost:9888/packages/sky/widgets/framework.dart:755:7)
E/chromium( 2105): #8      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1309:15)
E/chromium( 2105): #9      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium( 2105): 
E/WifiStateMachine(  754): WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=6c:f3:7f:ae:70:90 RSSI=-63
```
