### ISSUE TITLE
Material Design: Snackbar

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#83]
_From @eseidelGoogle on June 8, 2015 21:6_

We'll need a snackbar for our next demo:
http://www.google.com/design/spec/components/snackbars-toasts.html

The Android implementation of snackbars has more rounded corners than the original Material Design spec has.  We'll have to pick one.

_Copied from original issue: domokit/mojo#222_

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 23, 2015 0:56_

I'll take a look.

**Comment by Hixie** [comment]
_From @collinjackson on July 7, 2015 17:38_

@mpcomplete is working on animating this

**Comment by abarth** [comment]
We have this now.
