### ISSUE TITLE
Column height zero inside a Block seems wrong

### ISSUE THREAD

**Issue by collinjackson** [domokit/sky_engine#865]
Reduced test case: https://gist.github.com/collinjackson/935be7f8f664609a2baf

    // Copyright 2015 The Chromium Authors. All rights reserved.
    // Use of this source code is governed by a BSD-style license that can be
    // found in the LICENSE file.

    import 'dart:async';
    import 'package:sky/rendering/sky_binding.dart';
    import 'package:sky/widgets.dart';
    import 'package:sky/theme/colors.dart' as colors;

    void main() {
      runApp(new ColumnReducedTestCase());
      new Timer(new Duration(seconds: 2), () {
        SkyBinding.instance.debugDumpRenderTree();
      });
    }

    class ColumnReducedTestCase extends App {

      Widget build() {
        return new Center(
          child: new Container(
            decoration: new BoxDecoration(backgroundColor: colors.white),
            child: new Block([
              new Column([
                new Container(
                  margin: const EdgeDims.symmetric(vertical: 40.0),
                  height: 100.0,
                  width: 100.0,
                  decoration: new BoxDecoration(
                    backgroundColor: const Color(0x7FFF0000),
                    shape: Shape.circle
                  )
                )
              ])
            ])
          )
        );
      }
    }

Should look like this:

![screen](https://cloud.githubusercontent.com/assets/394889/9505392/f61be44e-4bf6-11e5-84a3-3da49cf5f706.png)

Instead it is a black screen.

Render tree:

    I/sky     (24767): Render Tree:
    I/sky     (24767): RenderView
    I/sky     (24767):   parentData: null
    I/sky     (24767):   constraints: null
    I/sky     (24767):   child: RenderPositionedBox
    I/sky     (24767):     parentData: <none>
    I/sky     (24767):     constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
    I/sky     (24767):     size: Size(360.0, 592.0)
    I/sky     (24767):     horizontal: 0.5
    I/sky     (24767):     vertical: 0.5
    I/sky     (24767):     child: RenderDecoratedBox relayoutSubtreeRoot=up1
    I/sky     (24767):       parentData: position=Point(0.0, 296.0)
    I/sky     (24767):       constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<592.0)
    I/sky     (24767):       size: Size(360.0, 0.0)
    I/sky     (24767):       decoration:
    I/sky     (24767):         backgroundColor: Color(0xffffffff)
    I/sky     (24767):       child: RenderSizeObserver relayoutSubtreeRoot=up2
    I/sky     (24767):         parentData: position=Point(0.0, 0.0)
    I/sky     (24767):         constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<592.0)
    I/sky     (24767):         size: Size(360.0, 0.0)
    I/sky     (24767):         child: RenderViewport relayoutSubtreeRoot=up3
    I/sky     (24767):           parentData: position=Point(0.0, 0.0)
    I/sky     (24767):           constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<592.0)
    I/sky     (24767):           size: Size(360.0, 0.0)
    I/sky     (24767):           child: RenderSizeObserver relayoutSubtreeRoot=up4
    I/sky     (24767):             parentData: position=Point(0.0, 0.0)
    I/sky     (24767):             constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<Infinity)
    I/sky     (24767):             size: Size(360.0, 0.0)
    I/sky     (24767):             child: RenderBlock relayoutSubtreeRoot=up5
    I/sky     (24767):               parentData: position=Point(0.0, 0.0)
    I/sky     (24767):               constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<Infinity)
    I/sky     (24767):               size: Size(360.0, 0.0)
    I/sky     (24767):               child 1: RenderFlex relayoutSubtreeRoot=up6
    I/sky     (24767):                 parentData: position=Point(0.0, 0.0)
    I/sky     (24767):                 constraints: BoxConstraints(360.0<=w<360.0, 0.0<=h<Infinity)
    I/sky     (24767):                 size: Size(360.0, 0.0)
    I/sky     (24767):                 direction: FlexDirection.vertical
    I/sky     (24767):                 justifyContent: FlexJustifyContent.start
    I/sky     (24767):                 alignItems: FlexAlignItems.center
    I/sky     (24767):                 textBaseline: null
    I/sky     (24767):                 child 1: RenderPadding relayoutSubtreeRoot=up7
    I/sky     (24767):                   parentData: position=Point(130.0, 0.0); flex=null
    I/sky     (24767):                   constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<Infinity)
    I/sky     (24767):                   size: Size(100.0, 180.0)
    I/sky     (24767):                   padding: EdgeDims(40.0, 0.0, 40.0, 0.0)
    I/sky     (24767):                   child: RenderConstrainedBox relayoutSubtreeRoot=up8
    I/sky     (24767):                     parentData: position=Point(0.0, 40.0)
    I/sky     (24767):                     constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<Infinity)
    I/sky     (24767):                     size: Size(100.0, 100.0)
    I/sky     (24767):                     additionalConstraints: BoxConstraints(100.0<=w<100.0, 100.0<=h<100.0)
    I/sky     (24767):                     child: RenderDecoratedBox
    I/sky     (24767):                       parentData: position=Point(0.0, 0.0)
    I/sky     (24767):                       constraints: BoxConstraints(100.0<=w<100.0, 100.0<=h<100.0)
    I/sky     (24767):                       size: Size(100.0, 100.0)
    I/sky     (24767):                       decoration:
    I/sky     (24767):                         backgroundColor: Color(0x7fff0000)
    I/sky     (24767):                         shape: Shape.circle

**Comment by Hixie** [comment]
@abarth fixed this, I think. It works now on trunk, anyway.
