### ISSUE TITLE
AssetImage doesn't always display

### ISSUE THREAD

**Issue by eseidelGoogle** [domokit/sky_engine#871]
I'm seeing this in all apps. Today I saw it in the FitnessApp with the hotdog icon for the drawer.  

There is a bug filed against NetworkImage specifically, but I'm seeing this with apk-loaded images as well:
https://github.com/domokit/sky_engine/issues/801

This is one of our most noticeable bugs at the moment.  @abarth or @collinjackson any theories?

**Comment by abarth** [comment]
Closing as dup of #801
