### ISSUE TITLE
TextStyle textAlign property fails

### ISSUE THREAD

**Issue by ppiet** [domokit/sky_engine#885]
_From @HansMuller on July 1, 2015 20:16_

Adding textAlign: TextAlign.center or TextAlign.right to the TextStyle created in interactive_flex.dart doesn't seem to have any effect. The TextStyle implementation appears to be doing the right thing but the text-align style change doesn't seem to be connected.

The TextStyle textAlign property is needed for correctly rendering tabs whose text labels wrap to two lines.

_Copied from original issue: domokit/mojo#291_

**Comment by ppiet** [comment]
Should this be moved to the sky_engine issue tracker?

**Comment by ppiet** [comment]
_From @eseidel on August 27, 2015 15:59_

You should feel welcome to move any issues you think might be better in sky_engine.  @Hixie tried to move most, but probably missed a couple.  I believe TextAlign works now, but I'm not sure.

https://github-issue-mover.appspot.com/ is a helpful tool if you need.

**Comment by abarth** [comment]
I believe this is fixed.  Please re-open if its not working.
