### ISSUE TITLE
FloatingActionButton onPressed callback is not executed when placed in a Positioned Flex on a Stack

### ISSUE THREAD

**Issue by turu** [domokit/sky_engine#918]
I'm having an issue as in the title. 
**Steps to reproduce:**
**1.** Create a widget tree like the one below:
```
(...)
Container(BoxConstraints.expand) [
  Stack [
    Positioned [
      Flex(FlexDirection.vertical, FlexJustifyContent.center) [[
        FloatingActionButton, 
        Flexible [
          Text
        ]
      ]]
    ]
  ]
] 
(...)
```
**2.** Click on the button.

**Expected result:**
**1.** Button's onPressed callback is executed.

**Actual result:**
**1.** Nothing happens.

To turn off failure mode remove the Flex and have a widget tree like:
```
(...)
Container(BoxConstraints.expand) [
  Stack [
    Positioned [
        FloatingActionButton
    ]
  ]
] 
(...)
```
I'm not sure if the problem is in Flex, in the Stack, in the Container or in the combination of them*. So far I was not able to produce a smaller example.

\* NOTE that there are some more Containers and Stacks higher up my actual widget tree, but that should not change anything.

**Comment by abarth** [comment]
Are you running with --checked ?  My guess is that you're hitting some asserts because you've marked the `Text` as `Flexible`.  We recently made a change whereby `Positioned` now gives its child unlimited space to work with.  If a widget is given unlimited space and is marked as `Flexible`, it will try to expand infinitely to fill that space, which causes problems (and should trigger an assert explaining the issue).

What happens if you remove the `Flexible` widget and just have the `Text` be a child of the `Flex` directly?

/cc @Hixie who has been poking around in this area.

**Comment by turu** [comment]
I'm running in production mode. Removing ```Flexible``` and having the ```Text``` directly as the second child of the ```Flex```, doesn't fix it. Removing ```Text``` entirely, leaving the button as the only child does not help either. Removing ```Flex``` does fix the issue. I will try to provide a self-contained repro ASAP.

**Comment by turu** [comment]
Here is the smallest example I was able to come up with that reproduces the problem:
```Dart
class ARedArmyApp extends App {
  @override
  Widget build() {
  return new Container(
        decoration: new BoxDecoration(backgroundColor: RedAccent[700]),
        child: new Stack([
      new Positioned(top: 100.0, left: 100.0, child:
//          new Column([
          new IconButton(
              color: Amber[600],
              icon: "action/grade",
              onPressed: () => print("I've been oppressed!"))
//      ])
          )
    ]));
  }
```
Uncomment to see the failure mode.

**Comment by abarth** [comment]
Thanks.  Will look this morning.

**Comment by abarth** [comment]
I have the repro

**Comment by abarth** [comment]
I have a fix.  Working up a patch now.  Nice bug.

**Comment by turu** [comment]
Thanks.
