### ISSUE TITLE
Anchor tags do not work in an iframe

### ISSUE THREAD

**Issue by Hixie** [domokit/sky_engine#92]
_From @MitchRudominer on May 27, 2015 4:40_

Below are the contents of three small .sky files. If I point the mojo shell at either test1.sky or test2.sky then the links work and I can navigate between test1 and test2. If I point the mojo shell at test.sky then I see test1 and test2 each rendered in an iframe and I see the links highlighted as if they are clickable but clicking on them does not have an effect.

test1.sky
```html
#!mojo mojo:sky_viewer
<sky>
<style>
 a { font-size: 1.642874em; line-height: 120%; display: paragraph; }
 h1 { font-size: 2em; margin: 1em; display: paragraph; }
 h2 { font-size: 1.2em; margin: 1em; display: paragraph;}
</style>
<h2>This is test 1</h1>
<a href='test2.sky'>test2</a>
</sky>
```
test2.sky
```html
#!mojo mojo:sky_viewer
<sky>
<style>
 a { font-size: 1.642874em; line-height: 120%; display: paragraph; }
 h1 { font-size: 2em; margin: 1em; display: paragraph; }
 h2 { font-size: 1.2em; margin: 1em; display: paragraph;}
</style>
<h2>This is test 2</h1>
<a href='test1.sky'>test1</a>
</sky>
```
test.sky
```html
#!mojo mojo:sky_viewer
<sky>
<h1>This is test</h1>
<iframe src="test1.sky" height=300></iframe>
<iframe src="test2.sky" height=300></iframe>
</sky>
```

_Copied from original issue: domokit/mojo#185_

**Comment by Hixie** [comment]
_From @eseidel on May 27, 2015 6:4_

The problem is we don't pass any services down to the child view.  This is a common problem in mojo embeddings and there are lots of TODO(beng) on the subject in various places where we do nested embedding:
https://github.com/domokit/mojo/blob/master/sky/engine/core/html/HTMLIFrameElement.cpp#

@jamesr

**Comment by Hixie** [comment]
The issue as originally framed is completely moot in the new world, since we have neither anchors nor iframes now.

Will the issue still be present in some different sense when we re-add the ability to nest Sky views?

cc @abarth @eseidelGoogle

**Comment by abarth** [comment]
Hard to say.  We should probably just close this issue and open a new one if that happens.  As written, this issue is non-actionable at the moment.
