### ISSUE TITLE
Source code link in Google Play is a dead link

### ISSUE THREAD

**Issue by Scorpiion** [domokit/sky_engine#948]
Hi @eseidel, the source code link in the play store is wrong, it an older now dead link: 

See play store here: 
https://play.google.com/store/apps/details?id=org.domokit.sky.demo

It links to this link:
https://github.com/domokit/mojo/tree/master/sky

The link is used at two places, in the description and in the "Visit website" link further down.

**Comment by eseidel** [comment]
Thanks!  I'll fix it on Monday.  @eseidelGoogle

**Comment by Scorpiion** [comment]
Sounds good, sorry if I linked to the wrong Github account. 

:+1:

**Comment by eseidel** [comment]
I am unexpectedly OOO for the next while.  @abarth has access to the developer console for Sky Demo and should be able to change the description.

**Comment by abarth** [comment]
Fixed.  Not sure how long it will take to propagate to the live site.  Thanks!

**Comment by Scorpiion** [comment]
Great! :+1:
